# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

  <canvas id="live2dcanvas" width="300" height="600" class="live2d"></canvas>
<%- live2d("live2dcanvas") %>
<style>
.live2d{
  position: fixed;
	bottom: -30px;
	right: 0px;
	z-index: 999;
	width: 150px;
	height: 300px;
  pointer-events: none;
}
</style>